title:            Trail of Sparks 
description:      Ryan Barrington Cox's blog. 
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://trailofsparks.org
#disqus_shortname: 'trailofsparks'

# Owner/author information
owner:
  name:           Ryan Barrington Cox
  avatar:         bio-photo.png
  bio:            "Ryan makes things in Asheville, North Carolina."
  email:          ryanbarrington@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # For Google Authorship https://plus.google.com/authorship
  google_plus: 
  youtube: ryanbarrybarrry
  github: ryanbarringtoncox
  twitter: barringtoncox
  facebook:
  stackoverflow:
  linkedin:
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-25926925-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Book Notes
    url: /book-notes
  - title: RSS
    url: /feed.xml
  - title: Etc
    url: /etc

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
#highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

gems:
  - jekyll-redirect-from

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
